// In this file you can specify the trial data for your experiment


const practice_trials = [
    {
        picture: "images/13_50_different.jpg.",
        question: "Are these blocks the same?",
        expected: "different",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        item: 13,
        rotation_deg: "50"
    },
    {
        picture: "images/13_50_same.jpg.",
        question: "Are these blocks the same?",
        expected: "same",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        item: 13,
        rotation_deg: "50"
    },
    {
        picture: "images/13_150_different.jpg.",
        question: "Are these blocks the same?",
        expected: "different",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        item: 13,
        rotation_deg: "150"
    },
    {
        picture: "images/13_150_same.jpg.",
        question: "Are these blocks the same?",
        expected: "same",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        item: 13,
        rotation_deg: "150"
    },
    {
        picture: "images/14_50_different.jpg.",
        question: "Are these blocks the same?",
        expected: "different",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        item: 14,
        rotation_deg: "50"
    },
    {
        picture: "images/14_50_same.jpg.",
        item: 14,
        question: "Are these blocks the same?",
        expected: "same",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        rotation_deg: "50"
    },
    {
        picture: "images/14_150_same.jpg",
        item: 14,
        question: "Are these blocks the same?",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        expected: "same",
        rotation_deg: 150
    },
    {
        picture: "images/14_150_different.jpg",
        item: 14,
        question: "Are these blocks the same?",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        expected: "different",
        rotation_deg: 150
    },
    {
        picture: "images/15_50_same.jpg",
        item: 15,
        question: "Are these blocks the same?",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        expected: "same",
        rotation_deg: 50
    },
    {
        picture: "images/15_50_different.jpg",
        item: 15,
        question: "Are these blocks the same?",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        expected: "different",
        rotation_deg: 50
    },
    {
        picture: "images/15_150_same.jpg",
        item: 15,
        question: "Are these blocks the same?",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        expected: "same",
        rotation_deg: 150
    },
    {
        picture: "images/15_150_different.jpg",
        item: 15,
        question: "Are these blocks the same?",
        key1: "f",
        key2: "j",
        f: "different",
        j: "same",
        expected: "different",
        rotation_deg: 150
    },
];

const main_trials = [
    {
       picture: "images/1_50_same.jpg",
       item: 1,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",

   },
   {
       picture: "images/1_50_different.jpg",
       item: 1,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",

   },
   {
       picture: "images/1_150_same.jpg",
       item: 1,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/1_150_different.jpg",
       item: 1,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/2_50_same.jpg",
       item: 2,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/2_50_different.jpg",
       item: 2,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/2_150_same.jpg",
       item: 2,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/2_150_different.jpg",
       item: 2,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },

   {
       picture: "images/3_50_same.jpg",
       item: 3,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/3_50_different.jpg",
       item: 3,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/3_150_same.jpg",
       item: 3,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/3_150_different.jpg",
       item: 3,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },

   {
       picture: "images/4_50_same.jpg",
       item: 4,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/4_50_different.jpg",
       item: 4,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/4_150_same.jpg",
       item: 4,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/4_150_different.jpg",
       item: 4,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },

   {
       picture: "images/5_50_same.jpg",
       item: 5,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/5_50_different.jpg",
       item: 5,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/5_150_same.jpg",
       item: 5,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/5_150_different.jpg",
       item: 5,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/6_50_same.jpg",
       item: 6,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/6_50_different.jpg",
       item: 6,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/6_150_same.jpg",
       item: 6,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/6_150_different.jpg",
       item: 6,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },

   {
       picture: "images/7_50_same.jpg",
       item: 7,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/7_50_different.jpg",
       item: 7,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/7_150_same.jpg",
       item: 7,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/7_150_different.jpg",
       item: 7,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },

   {
       picture: "images/8_50_same.jpg",
       item: 8,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/8_50_different.jpg",
       item: 8,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/8_150_same.jpg",
       item: 8,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/8_150_different.jpg",
       item: 8,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },

   {
       picture: "images/9_50_same.jpg",
       item: 9,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/9_50_different.jpg",
       item: 9,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/9_150_same.jpg",
       item: 9,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/9_150_different.jpg",
       item: 9,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/10_50_same.jpg",
       item: 10,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/10_50_different.jpg",
       item: 10,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/10_150_same.jpg",
       item: 10,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/10_150_different.jpg",
       item: 10,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/11_50_same.jpg",
       item: 11,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/11_50_different.jpg",
       item: 11,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/11_150_same.jpg",
       item: 11,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/11_150_different.jpg",
       item: 11,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/12_50_same.jpg",
       item: 12,
       expected: "same",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/12_50_different.jpg",
       item: 12,
       expected: "different",
       rotation_deg: 50,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/12_150_same.jpg",
       item: 12,
       expected: "same",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
   {
       picture: "images/12_150_different.jpg",
       item: 12,
       expected: "different",
       rotation_deg: 150,
       question: "Are these blocks the same?",
       key1: "f",
       key2: "j",
       f: "different",
       j: "same",
   },
];
